from .ws_messages import *
from .entities import *

ENTITY_MODELS: dict[Platform, HAEntity] = {
    Platform.ALARM_CONTROL_PANEL: AlarmControlPanelEntity,
    Platform.BINARY_SENSOR: BinarySensorEntity,
    Platform.BUTTON: ButtonEntity,
    Platform.CALENDAR: CalendarEntity,
    Platform.CAMERA: CameraEntity,
    Platform.CLIMATE: ClimateEntity,
    Platform.CONVERSATION: ConversationEntity,
    Platform.COVER: CoverEntity,
    Platform.DATE: DateEntity,
    Platform.DATETIME: DateTimeEntity,
    Platform.DEVICE_TRACKER: DeviceTrackerEntity,
    Platform.EVENT: EventEntity,
    Platform.FAN: FanEntity,
    Platform.HUMIDIFIER: HumidifierEntity,
    Platform.IMAGE: ImageEntity,
    Platform.LAWN_MOWER: LawnMowerEntity,
    Platform.LIGHT: LightEntity,
    Platform.LOCK: LockEntity,
    Platform.MEDIA_PLAYER: MediaPlayerEntity,
    Platform.NOTIFY: NotifyEntity,
    Platform.NUMBER: NumberEntity,
    Platform.REMOTE: RemoteEntity,
    Platform.SCENE: SceneEntity,
    Platform.SELECT: SelectEntity,
    Platform.SENSOR: SensorEntity,
    Platform.SIREN: SirenEntity,
    Platform.STT: STTEntity,
    Platform.SWITCH: SwitchEntity,
    Platform.TEXT: TextEntity,
    Platform.TIME: TimeEntity,
    Platform.TODO: TodoListEntity,
    Platform.TTS: TTSEntity,
    Platform.VACUUM: VacuumEntity,
    Platform.VALVE: ValveEntity,
    Platform.UPDATE: UpdateEntity,
    Platform.WAKE_WORD: WakeWordEntity,
    Platform.WATER_HEATER: WaterHeaterEntity,
    Platform.WEATHER: WeatherEntity,
}
